# Generated by Django 4.2.1 on 2023-05-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Maqola',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
