# Generated by Django 4.2.1 on 2023-05-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
