# Generated by Django 4.2.1 on 2023-05-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profil_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
    ]
